# Max level a trader can level up to.
# Levels are not yet implemented
max_level: 1

# Whether a trader NPC that gave a mission will replace the taken mission when
# it is completed/failed. If false, then players will have to wait for the mission
# to refresh on the normal timer (mission_refresh_interval).
replace_mission_on_completion: true
replace_mission_on_failure: false

# Whether missions should be announced to other players
announce_mission_starts: true
# Distance player needs to be from the mission start location to get the announcement
announce_mission_distance: 10000

# There should be one entry under levels for every level from 1 to `max_level`.
# For example, if you have `max_level` set to 4, you should have keys for levels 1, 2, 3, and 4.
# Each of the options under this part of the config can change with the level of a trader.
# You could for example increase the number of missions a trader is able to offer at once
# by increasing the value of `trader_max_missions` for increasingly higher trader levels.
# If you want everything to stay the same as for level 1, you can just set the value of a level
# key to *level_template.
levels:

  1: &level_template
    caravan_health: 80.0 # Max health of the pack animal used to carry goods

    # Time in between missions refreshing
    mission_refresh_interval: 60 # In minutes

    # The maximum number of trade routes an individual trader can have at a given time.
    # Max is 36.
    trader_max_missions: 10

    # Minimum and maximum distance between two traders for trade missions to be available
    min_route_distance: 300
    max_route_distance: 10000

    # The average value of rewards offered for missions of distance `base_reward_scaling_distance`
    base_reward_value: 1024

    # The average value of the items required for missions of distance `base_reward_scaling_distance`
    base_requirements_value: 512

    # How much the reward and requirements can fluctuate for any given missions
    # Making these numbers too low (i.e. <0.1) may result in no rewards for some missions
    reward_fluctuation_fraction: 0.2 # 0.2 = plus or minus 20% reward
    requirements_fluctuation_fraction: 0.2 # 0.2 = plus or minus 20% requirements

    # Minimum and maximum multipliers for the reward and requirements value based on distance travelled to complete the mission
    min_reward_scaling_multiplier: 0.1 # 0.5
    max_reward_scaling_multiplier: 10.0 # 4.0

    min_requirements_scaling_multiplier: 0.4
    max_requirements_scaling_multiplier: 3.0

    # Minimum and maximum unique number of items in the required and reward lists
    min_reward_unique_items: 1
    max_reward_unique_items: 4

    min_requirements_unique_items: 1
    max_requirements_unique_items: 3

    # Reward and requirements multiplier equals:
    #   1 - when mission distance is `base_X_scaling_distance`
    #   `min_X_scaling_multiplier` - when mission distance <= `min_X_scaling_distance`
    #   `max_X_scaling_multiplier` - when mission distance >= `max_X_scaling_distance`
    min_reward_scaling_distance: 500
    base_reward_scaling_distance: 1000
    max_reward_scaling_distance: 5000

    min_requirements_scaling_distance: 500
    base_requirements_scaling_distance: 1000
    max_requirements_scaling_distance: 5000


    ###################################################################################################
    #                                                                                                 #
    # The following sections define items that can be given as a reward for trade missions,           #
    # and the requirements for these missions.                                                        #
    #                                                                                                 #
    # This part of the config follows the following format:                                           #
    #                                                                                                 #
    # mission_<reward|requirement>_pool:                                                              #
    #   <category_name>: # This can be whatever you want, just no repeats                             #
    #     weight: <integer>  # Relative probability of selecting this category                        #
    #     min_amount: <integer>  # Optional: Default minimum quantity for items in this category      #
    #     max_amount: <integer>  # Optional: Default maximum quantity for items in this category      #
    #     items:                                                                                      #
    #       - item: <ITEM_NAME>  # Minecraft item name (all caps)                                     #
    #         weight: <integer>  # Optional: Relative probability within category                     #
    #         min_amount: <integer>  # Optional: Overrides category minimum                           #
    #         max_amount: <integer>  # Optional: Overrides category maximum                           #
    #                                                                                                 #
    # Notes:                                                                                          #
    # - List of all possible items: https://jd.papermc.io/paper/1.21.1/org/bukkit/Material.html       #
    # - Weights are the unnormalized probability of selecting an item                                 #
    # - If weight is omitted for an item or category, it defaults to 1                                #
    # - If min_amount and max_amount are omitted for an item, it uses category defaults or 1          #
    # - Weights within a category are relative to that category's total weight                        #
    # - You can add as many categories and items as needed                                            #
    # - Weights can be set to 0 to effectively disable a category or item                             #
    #                                                                                                 #
    ###################################################################################################
    
    mission_reward_pool: &reward_pool_template
      equipment:
        weight: 1
        items:
          - item: DIAMOND_SWORD
          - item: DIAMOND_AXE
          - item: DIAMOND_PICKAXE
          - item: DIAMOND_SHOVEL
          - item: DIAMOND_HOE
          - item: DIAMOND_HELMET
          - item: DIAMOND_CHESTPLATE
          - item: DIAMOND_LEGGINGS
          - item: DIAMOND_BOOTS

      valuables:
        weight: 5
        items:
          - item: QUARTZ
            min_amount: 8
            max_amount: 256
          - item: COAL
            min_amount: 8
            max_amount: 256
          - item: LAPIS_LAZULI
            min_amount: 8
            max_amount: 256
          - item: REDSTONE
            min_amount: 8
            max_amount: 128
          - item: COPPER_INGOT
            min_amount: 8
            max_amount: 192
          - item: IRON_INGOT
            min_amount: 4
            max_amount: 128
          - item: GOLD_INGOT
            min_amount: 2
            max_amount: 128
          - item: EMERALD
            max_amount: 64
          - item: DIAMOND
            max_amount: 32
          - item: NETHERITE_SCRAP
            max_amount: 8
          - item: NETHERITE_INGOT
            max_amount: 4

      tnt:
        weight: 2
        items:
          - item: TNT
            max_amount: 64

      wood:
        weight: 3
        min_amount: 8
        max_amount: 512
        items:
          - item: OAK_LOG
            weight: 4
          - item: SPRUCE_LOG
            weight: 2
          - item: BIRCH_LOG
          - item: ACACIA_LOG
          - item: DARK_OAK_LOG
            weight: 3
          - item: CHERRY_LOG
            weight: 2
          - item: MANGROVE_LOG

      building_materials:
        weight: 2
        min_amount: 64
        max_amount: 512
        items:
          - item: COBBLESTONE
            max_amount: 1024
          - item: SAND
            max_amount: 1024
          - item: STONE
          - item: SANDSTONE
          - item: GLASS
          - item: ICE
            min_amount: 8
            max_amount: 128
          - item: PRISMARINE
            max_amount: 256
          - item: GLOWSTONE
            min_amount: 4
            max_amount: 128
          - item: AMETHYST_BLOCK
            min_amount: 4
            max_amount: 128

      terracotta:
        weight: 2
        min_amount: 16
        max_amount: 512
        items:
          - item: WHITE_TERRACOTTA
          - item: ORANGE_TERRACOTTA
          - item: MAGENTA_TERRACOTTA
          - item: LIGHT_BLUE_TERRACOTTA
          - item: YELLOW_TERRACOTTA
          - item: LIME_TERRACOTTA
          - item: PINK_TERRACOTTA
          - item: GRAY_TERRACOTTA
          - item: LIGHT_GRAY_TERRACOTTA
          - item: CYAN_TERRACOTTA
          - item: PURPLE_TERRACOTTA
          - item: BLUE_TERRACOTTA
          - item: BROWN_TERRACOTTA
          - item: GREEN_TERRACOTTA
          - item: RED_TERRACOTTA
          - item: BLACK_TERRACOTTA

      concrete:
        weight: 2
        min_amount: 16
        max_amount: 512
        items:
          - item: WHITE_CONCRETE
          - item: ORANGE_CONCRETE
          - item: MAGENTA_CONCRETE
          - item: LIGHT_BLUE_CONCRETE
          - item: YELLOW_CONCRETE
          - item: LIME_CONCRETE
          - item: PINK_CONCRETE
          - item: GRAY_CONCRETE
          - item: LIGHT_GRAY_CONCRETE
          - item: CYAN_CONCRETE
          - item: PURPLE_CONCRETE
          - item: BLUE_CONCRETE
          - item: BROWN_CONCRETE
          - item: GREEN_CONCRETE
          - item: RED_CONCRETE
          - item: BLACK_CONCRETE

      xp:
        weight: 4
        items:
          - item: EXPERIENCE_BOTTLE
            min_amount: 4
            max_amount: 128

      spawn_eggs:
        weight: 1
        max_amount: 4
        items:
          - item: CHICKEN_SPAWN_EGG
          - item: PIG_SPAWN_EGG
          - item: AXOLOTL_SPAWN_EGG
          - item: BEE_SPAWN_EGG
          - item: CAT_SPAWN_EGG
          - item: CAMEL_SPAWN_EGG
          - item: DOLPHIN_SPAWN_EGG
          - item: FOX_SPAWN_EGG
          - item: GOAT_SPAWN_EGG
          - item: OCELOT_SPAWN_EGG
          - item: PARROT_SPAWN_EGG
          - item: HORSE_SPAWN_EGG
            max_amount: 2
          - item: BLAZE_SPAWN_EGG
            max_amount: 2
          - item: CREEPER_SPAWN_EGG
            max_amount: 2
          - item: VILLAGER_SPAWN_EGG
            max_amount: 2
          - item: WANDERING_TRADER_SPAWN_EGG
            max_amount: 1
          - item: WITHER_SPAWN_EGG
            max_amount: 1

      misc:
        weight: 1
        items:
          - item: SPONGE
            weight: 2
            max_amount: 32
          - item: NAUTILUS_SHELL
            weight: 3
            max_amount: 4
          - item: HEART_OF_THE_SEA

    mission_requirement_pool: &requirement_pool_template
      valuables:
        weight: 8
        items:
          - item: QUARTZ
            min_amount: 8
            max_amount: 256
          - item: COAL
            min_amount: 8
            max_amount: 256
          - item: LAPIS_LAZULI
            min_amount: 8
            max_amount: 256
          - item: REDSTONE
            min_amount: 8
            max_amount: 128
          - item: COPPER_INGOT
            min_amount: 8
            max_amount: 192
          - item: IRON_INGOT
            min_amount: 4
            max_amount: 128
          - item: GOLD_INGOT
            min_amount: 2
            max_amount: 128
          - item: EMERALD
            min_amount: 1
            max_amount: 64
          - item: DIAMOND
            min_amount: 1
            max_amount: 32

      wood:
        weight: 4
        min_amount: 16
        max_amount: 512
        items:
          - item: OAK_LOG
          - item: SPRUCE_LOG
          - item: BIRCH_LOG
          - item: ACACIA_LOG
          - item: DARK_OAK_LOG
          - item: CHERRY_LOG
          - item: MANGROVE_LOG

      mob_drops:
        weight: 8
        max_amount: 128
        items:
          - item: EGG
          - item: BONE
          - item: STRING
          - item: GUNPOWDER
          - item: FEATHER
          - item: SPIDER_EYE
          - item: BLAZE_ROD
            max_amount: 32

      building_materials:
        weight: 4
        min_amount: 16
        max_amount: 512
        items:
          - item: COBBLESTONE
            min_amount: 128
            max_amount: 1024
          - item: SAND
            min_amount: 128
            max_amount: 1024
          - item: STONE
          - item: SANDSTONE
          - item: GLASS

      terracotta:
        weight: 4
        min_amount: 16
        max_amount: 512
        items:
          - item: WHITE_TERRACOTTA
          - item: ORANGE_TERRACOTTA
          - item: MAGENTA_TERRACOTTA
          - item: LIGHT_BLUE_TERRACOTTA
          - item: YELLOW_TERRACOTTA
          - item: LIME_TERRACOTTA
          - item: PINK_TERRACOTTA
          - item: GRAY_TERRACOTTA
          - item: LIGHT_GRAY_TERRACOTTA
          - item: CYAN_TERRACOTTA
          - item: PURPLE_TERRACOTTA
          - item: BLUE_TERRACOTTA
          - item: BROWN_TERRACOTTA
          - item: GREEN_TERRACOTTA
          - item: RED_TERRACOTTA
          - item: BLACK_TERRACOTTA

      wool:
        weight: 4
        max_amount: 128
        items:
          - item: WHITE_WOOL
          - item: ORANGE_WOOL
          - item: MAGENTA_WOOL
          - item: LIGHT_BLUE_WOOL
          - item: YELLOW_WOOL
          - item: LIME_WOOL
          - item: PINK_WOOL
          - item: GRAY_WOOL
          - item: LIGHT_GRAY_WOOL
          - item: CYAN_WOOL
          - item: PURPLE_WOOL
          - item: BLUE_WOOL
          - item: BROWN_WOOL
          - item: GREEN_WOOL
          - item: RED_WOOL
          - item: BLACK_WOOL

      fish:
        weight: 2
        max_amount: 32
        items:
          - item: salmon
          - item: cod

      misc:
        weight: 4
        items:
          - item: PAPER
            min_amount: 4
            max_amount: 128
          - item: MAP
            max_amount: 32
          - item: COMPASS
            max_amount: 32
          - item: FURNACE
            min_amount: 4
            max_amount: 64
          - item: CRAFTING_TABLE
            min_amount: 4
            max_amount: 64
          - item: SLIME_BALL
            min_amount: 2
            max_amount: 128

      music_discs:
        weight: 1
        items:
          - item: MUSIC_DISC_13
          - item: MUSIC_DISC_CAT
          - item: MUSIC_DISC_BLOCKS
          - item: MUSIC_DISC_CHIRP
          - item: MUSIC_DISC_CREATOR
          - item: MUSIC_DISC_CREATOR_MUSIC_BOX
          - item: MUSIC_DISC_FAR
          - item: MUSIC_DISC_MALL
          - item: MUSIC_DISC_MELLOHI
          - item: MUSIC_DISC_STAL
          - item: MUSIC_DISC_STRAD
          - item: MUSIC_DISC_WARD
          - item: MUSIC_DISC_11
          - item: MUSIC_DISC_WAIT
          - item: MUSIC_DISC_OTHERSIDE
          - item: MUSIC_DISC_RELIC
          - item: MUSIC_DISC_5
          - item: MUSIC_DISC_PIGSTEP
          - item: MUSIC_DISC_PRECIPICE



  # These are not used yet
  # 2: *level_template
  # 3:
  #   <<: *level_template
  #   caravan_health: 100.0
  #   mission_refresh_interval: 30 # In minutes