
### Valuables ###

COAL: 16
LAPIS_LAZULI: 16
COPPER_INGOT: 16
IRON_INGOT: 32
GOLD_INGOT: 64
EMERALD: 128
DIAMOND: 512
NETHERITE_SCRAP: 512
NETHERITE_INGOT: 2304

COAL_BLOCK: 144
LAPIS_BLOCK: 144
COPPER_BLOCK: 144
IRON_BLOCK: 288
GOLD_BLOCK: 576
EMERALD_BLOCK: 1152
DIAMOND_BLOCK: 4608
NETHERITE_BLOCK: 20736

### Common Items ###

COBBLESTONE: 1
DIRT: 1
GRAVEL: 1
SAND: 1

COBBLED_DEEPSLATE: 2
BASALT: 2
BLACKSTONE: 2
CALCITE: 2
TUFF: 2

OAK_LEAVES: 2
SPRUCE_LEAVES: 2
BIRCH_LEAVES: 2
JUNGLE_LEAVES: 2
ACACIA_LEAVES: 2
DARK_OAK_LEAVES: 2
CHERRY_LEAVES: 2
MANGROVE_LEAVES: 2

STONE: 4
SANDSTONE: 4
GRASS_BLOCK: 4
ICE: 4
GLASS: 4
PRISMARINE: 4
REDSTONE: 4
QUARTZ: 4

OAK_LOG: 4
SPRUCE_LOG: 4
BIRCH_LOG: 4
JUNGLE_LOG: 4
ACACIA_LOG: 4
DARK_OAK_LOG: 4
CHERRY_LOG: 4
MANGROVE_LOG: 4

WHITE_TERRACOTTA: 4
ORANGE_TERRACOTTA: 4
MAGENTA_TERRACOTTA: 4
LIGHT_BLUE_TERRACOTTA: 4
YELLOW_TERRACOTTA: 4
LIME_TERRACOTTA: 4
PINK_TERRACOTTA: 4
GRAY_TERRACOTTA: 4
LIGHT_GRAY_TERRACOTTA: 4
CYAN_TERRACOTTA: 4
PURPLE_TERRACOTTA: 4
BLUE_TERRACOTTA: 4
BROWN_TERRACOTTA: 4
GREEN_TERRACOTTA: 4
RED_TERRACOTTA: 4
BLACK_TERRACOTTA: 4

WHITE_CONCRETE: 4
ORANGE_CONCRETE: 4
MAGENTA_CONCRETE: 4
LIGHT_BLUE_CONCRETE: 4
YELLOW_CONCRETE: 4
LIME_CONCRETE: 4
PINK_CONCRETE: 4
GRAY_CONCRETE: 4
LIGHT_GRAY_CONCRETE: 4
CYAN_CONCRETE: 4
PURPLE_CONCRETE: 4
BLUE_CONCRETE: 4
BROWN_CONCRETE: 4
GREEN_CONCRETE: 4
RED_CONCRETE: 4
BLACK_CONCRETE: 4

CRAFTING_TABLE: 8
FURNACE: 8

PAPER: 12

AMETHYST_BLOCK: 16
GLOWSTONE: 16
EXPERIENCE_BOTTLE: 16

SLIME_BALL: 24

WHITE_WOOL: 24
ORANGE_WOOL: 24
MAGENTA_WOOL: 24
LIGHT_BLUE_WOOL: 24
YELLOW_WOOL: 24
LIME_WOOL: 24
PINK_WOOL: 24
GRAY_WOOL: 24
LIGHT_GRAY_WOOL: 24
CYAN_WOOL: 24
PURPLE_WOOL: 24
BLUE_WOOL: 24
BROWN_WOOL: 24
GREEN_WOOL: 24
RED_WOOL: 24
BLACK_WOOL: 24

OBSIDIAN: 32

TNT: 64
SPONGE: 64

MAP: 108

COMPASS: 132

NAUTILUS_SHELL: 128
HEART_OF_THE_SEA: 1024

### Fish ###

SALMON: 12
COD: 12

### Spawn Eggs ###

CHICKEN_SPAWN_EGG: 128
PIG_SPAWN_EGG: 128
AXOLOTL_SPAWN_EGG: 128
BEE_SPAWN_EGG: 128
CAT_SPAWN_EGG: 128
CAMEL_SPAWN_EGG: 128
DOLPHIN_SPAWN_EGG: 128
FOX_SPAWN_EGG: 128
GOAT_SPAWN_EGG: 128
OCELOT_SPAWN_EGG: 128
PARROT_SPAWN_EGG: 128

HORSE_SPAWN_EGG: 256
BLAZE_SPAWN_EGG: 256
CREEPER_SPAWN_EGG: 256

VILLAGER_SPAWN_EGG: 512
WANDERING_TRADER_SPAWN_EGG: 512

WITHER_SPAWN_EGG: 1024

### Mob Drops ###

EGG: 16
BONE: 16
STRING: 16
GUNPOWDER: 16
FEATHER: 16
SPIDER_EYE: 16
BLAZE_ROD: 64

### Equipment ###

DIAMOND_SWORD: 1024
DIAMOND_SHOVEL: 512
DIAMOND_PICKAXE: 1536
DIAMOND_AXE: 1536
DIAMOND_HOE: 1024

DIAMOND_HELMET: 2560
DIAMOND_CHESTPLATE: 4096
DIAMOND_LEGGINGS: 3584
DIAMOND_BOOTS: 2048

ELYTRA: 10000

### Other ###

MUSIC_DISC_13: 4096
MUSIC_DISC_CAT: 4096
MUSIC_DISC_BLOCKS: 4096
MUSIC_DISC_CHIRP: 4096
MUSIC_DISC_CREATOR: 4096
MUSIC_DISC_CREATOR_MUSIC_BOX: 4096
MUSIC_DISC_FAR: 4096
MUSIC_DISC_MALL: 4096
MUSIC_DISC_MELLOHI: 4096
MUSIC_DISC_STAL: 4096
MUSIC_DISC_STRAD: 4096
MUSIC_DISC_WARD: 4096
MUSIC_DISC_11: 4096
MUSIC_DISC_WAIT: 4096
MUSIC_DISC_OTHERSIDE: 4096
MUSIC_DISC_RELIC: 4096
MUSIC_DISC_5: 4096
MUSIC_DISC_PIGSTEP: 4096
MUSIC_DISC_PRECIPICE: 4096