name: TradeRoutes
version: '1.0-SNAPSHOT'
main: io.github.ejmejm.tradeRoutes.TradeRoutes
author: 'Edan Meyer'
api-version: '1.21'
depend: [FancyNpcs]
softdepend: [Towny]

commands:
  traderoutes:
    aliases: [tr]
    description: "Command for everything TradeRoutes related"
    permission: traderoutes.command

permissions:


  ### Base plugin command ###

  traderoutes.command:
    description: "Ability to use the tr command for help"
    default: true


  ### Commands for broad player groups ###

  traderoutes.command.players:
    description: "Commands that all standard players should have access to"
    default: op
    children:
      traderoutes.command: true
      traderoutes.command.list.*: true
      traderoutes.command.mission.cancel: true
      traderoutes.command.confirm: true

  traderoutes.command.mayor:
    description: "Commands that all town mayors should have access to"
    default: op
    children:
      traderoutes.command.players: true
      traderoutes.command.trader.spawn.town: true
      traderoutes.command.trader.remove.town: true

  traderoutes.command.admin:
    description: "Ability to use all list commands"
    default: op
    children:
      traderoutes.command.mayor: true
      traderoutes.command.trader.*: true


  ### All wild card commands ###

  traderoutes.command.list.*:
    description: "Ability to use all list commands"
    default: op
    children:
      traderoutes.command.list.traders: true
      traderoutes.command.list.missions: true

  traderoutes.command.trader.*:
    description: "Commands related to traders"
    default: op
    children:
      traderoutes.command.trader.spawn.town: true
      traderoutes.command.trader.spawn.any: true
      traderoutes.command.trader.remove.town: true
      traderoutes.command.trader.remove.any: true


  ### All single commands ###

  traderoutes.command.list.traders:
    description: "Ability to list all traders in the world"
    default: op
  traderoutes.command.list.missions:
    description: "Ability to list all active missions in the world"
    default: op

  traderoutes.command.trader.spawn.town:
    description: "Ability to spawn a trade route NPC for their town in their land"
    default: op
  traderoutes.command.trader.spawn.any:
    description: "Ability to spawn a trader with an arbitrary affiliation"
    default: op
  traderoutes.command.trader.remove.town:
    description: "Ability to remove a trader from their town"
    default: op
  traderoutes.command.trader.remove.any:
    description: "Ability to remove a trader with an arbitrary affiliation"
    default: op

  traderoutes.command.mission.cancel:
    description: "Ability to cancel your own active mission"
    default: op
  traderoutes.command.confirm:
    description: "Ability to confirm one of multiple possible actions"
    default: op
