name: TradeRoutes
version: '1.0-SNAPSHOT'
main: io.github.ejmejm.tradeRoutes.TradeRoutes
author: 'Edan Meyer'
api-version: '1.21'
depend: [FancyNpcs]
softdepend: [Towny]

commands:
  traderoutes:
    aliases: [tr]
    description: "Command for everything TradeRoutes related"
    permission: traderoutes.command

permissions:
  traderoutes.command:
    description: "Ability to use the tr command for help"
    default: true
  traderoutes.command.spawn.trader.town:
    description: "Ability to spawn a trade route NPC for their town in their land"
    default: op
  traderoutes.command.spawn.trader.any:
    description: "Ability to spawn a trader with an arbitrary affiliation"
    default: op